### ISSUE TITLE
Skriveleif vistitors 

### ISSUE THREAD

**Issue by andersnese** [thomand/dashboard#1]

**Comment by thomand** [comment]
Haha. Jeg bare fortsatte med den siden du hadde skrevet feil opprinnelig :) Har ikke funnet ut hvordan jeg endrer navn på rotelementer i firebase. Må slette hele visitors og lage den på nytt, så vidt jeg kan se. Du kan se om du finner ut en måte å endre det på, så kan jeg endre det deretter i JS. Ikke noe stress egentlig da, ettersom det kun er i backend?

**Comment by thomand** [comment]
fixed
