### ISSUE TITLE
Noe ny data i tom placeholder side 2

### ISSUE THREAD

**Issue by thomand** [thomand/dashboard#11]

**Comment by andersnese** [comment]
Besøk på studiesidene fordelt på måneder. 

Eksempeldata:
01 : 434343
02: 4344334
03: 34343
04: 113227
osv.

**Comment by andersnese** [comment]
Data er lagt inn i firebase under study/visitsByMonth

Jeg tenker kanskje et søylediagram, hva tenker du?

**Comment by thomand** [comment]
Fikset to linjediagram i samme chart.
