### ISSUE TITLE
Topp 10 på gemini siste 30 dager

### ISSUE THREAD

**Issue by andersnese** [thomand/dashboard#12]
Legg til forklaring for når det dataene er hentet fra (siste 30 dager)

**Comment by thomand** [comment]
Fikk spørsmål fra Tore om hvor dataene fra gemini kom fra. Snakket om GA og at han forsøkte å få tilgang der nå. Det er visst også en "mest lest" på gemini.no som jeg ikke har sett. Burde oppdatere skriptet til å hente derfra istedet. I alle fall som en midlertidig fix før GA kommer på banen. Skal se om jeg får fikset det.

**Comment by thomand** [comment]
30 days lagt til
