### ISSUE TITLE
Forslag til informasjon som kan vises på innsida-slide(s)

### ISSUE THREAD

**Issue by andersnese** [thomand/dashboard#14]
1. Get visits by weekday from behavior (hele Innsida). 
   Eksempeldata:
     "page_views": 246284,
     "visits": 54969,
     "day_of_week": 1
2. Get visits by hour of the day from behavior (hele Innsida)
   Eksempeldata:
     "page_views": 3487,
     "visits": 1138,
     "hour_of_day": 0

3.
3a. Get most popular pages from content (WIKI-sider)
3b. Get most popular pages from content (TEMA-sider)
3c. Get least popular pages from content (TEMA-sider)
4. Visits this week vs last week 
5. Change in visits last week, month, year (lik første sliden)

**Comment by thomand** [comment]
Kan man få ut live antall brukere på innsida også slik som på ntnu.no? @andersnese Snakket med Martin om det og det er noen som har stusset over det lave tallet på antall brukere på ntnu. Så hvis vi får tall for innsida også, så blir det litt klarere at det er snakk om to forskjellige ting. Altså internt og eksternt..

**Comment by thomand** [comment]
pkt 3-5 er implementert.
