### ISSUE TITLE
Browsers api struktur 

### ISSUE THREAD

**Issue by andersnese** [thomand/dashboard#2]
Burde være mer fleksibel for nye type browsere (for eksempel Edge)

**Comment by thomand** [comment]
Slik det er nå kan det relativt enkelt legges til flere browsere. Koden må oppdateres litt, men ikke mye. Må legge til aktuell browsers logo i prosjektet, legge den til under browsere i firebase og ta inn den nye browseren i JS-koden (updateBrowserTable() ) og sende den til sortering. Ellers så vil koden fungere som vanlig med at den sorterer på flest besøk og viser topp 5.

**Comment by andersnese** [comment]
sweet!
